### ISSUE TITLE
3.3.2 testing

### ISSUE THREAD

**Issue by Mathelab** [Mathelab/ALTRE#13]
Test package on 3.3.2 and ensure it works.

**Comment by osubmi784323** [comment]
Shouldn't this say 3.2.0? I tested the installation on Andy's computer using the github readme and it fails on R 3.2.0. The bioconductor packages install but when the line devtools::install_github("mathelab/ALTRE") is run and it is automatically installing the other R packages it fails on the installation of the readr R package.

**Comment by rfarouni** [comment]
you need to modify the description file Depends: R (>= 3.2.0)

**Comment by baskineliz** [comment]
I did try that, it didn’t work for me.

**Comment by Mathelab** [comment]
Got it to work but had to do lots of manual installations:

need to install gfortran version-4.2 first 

install.packages("devtools")  
source("http://bioconductor.org/biocLite.R")
install.packages(“sourcetools”)
install.packages(“Matrix”)
install.packages(“shiny”)
install.packages(“rmarkdown”)
install.packages(“shinydashboard”)
install.packages(“shinyFiles”)
biocLite(“AnnotationHub”)
biocLite(“rGREAT”)
BiocInstaller::biocLite(c(
                        'org.Hs.eg.db',
                        'EnsDb.Hsapiens.v75',
                        ‘GO.db’, 
            ‘dplyr',
                        ‘ensembldb’,
                        ‘genefilter’,
                        ‘DESeq2’))
install.packages(“highcharter”)
install.packages(“readr”)
devtools::install_github("mathelab/ALTRE", ref="webgraphs")
