### ISSUE TITLE
Rounding

### ISSUE THREAD

**Issue by rfarouni** [Mathelab/ALTRE#19]
I am not sure if rounding is necessary  [here](https://github.com/Mathelab/ALTRE/blob/webgraphs/R/plottingfunctions.R#L563) . We just need to have Highcharts format the output. A quick web search gave me this

`
  tooltip: {
     formatter: function() {
        return '<b>'+ this.point.name +'</b>: '+ Math.round(this.percentage) +' %';
     }
  }
`

**Comment by osubmi784323** [comment]
I change it, but I couldn't figure out how to use this code.

I ended up using:  hc_tooltip(valueDecimals = 2)
