### ISSUE TITLE
Volcano plot

### ISSUE THREAD

**Issue by rfarouni** [Mathelab/ALTRE#23]
The [Volcano plot](https://github.com/Mathelab/ALTRE/blob/webgraphs/R/plottingfunctions.R#L353) takes a very long time to render

**Comment by osubmi784323** [comment]
I don't know how I would fix it? It takes no time in the R-package in my experience? This is R-shiny specific?

**Comment by rfarouni** [comment]
I am not sure. I keep getting this progress bar. Do you know what function prints it?
`
|===========================          | 25% ~7 s remaining     
`

**Comment by rfarouni** [comment]
After dozens of experiments and modifications, I am still not unable to get it to display. Whatever the problem is, it is most probably not connected to
- other elements in the display
- the grid form of the output
- highcharts

I have a lurking suspicion that  it is caused by shinyFiles and this warning in particular
`
Found more than one class "connection" in cache; using the first, from namespace 'BiocGenerics'
`
One thing we can do is plot some fake data in the volcano plot and see what happens Another thing we can do is disable shinyFiles.

**Comment by rfarouni** [comment]
I have added a temporary scatter plot function that is similar to the volcano plot but uses a small dataset that is read inside the function from a character object.  The plots renders without a problem in the Shiny app. We need to try to read the entire data with the peaks inside the function to rule out data size or format.

**Comment by Mathelab** [comment]
This works on my mac, is it still a problem in linux?

**Comment by rfarouni** [comment]
Data trimming seems to work for now
