### ISSUE TITLE
Reshape2

### ISSUE THREAD

**Issue by rfarouni** [Mathelab/ALTRE#24]
The  reshape2 package is not needed if we are using tidyr. This line needs to be changed

https://github.com/Mathelab/ALTRE/blob/webgraphs/R/plottingfunctions.R#L291

**Comment by ewymathe** [comment]
What does this line have to do with reshape2?

**Comment by rfarouni** [comment]
The line  number shifted after an update. It is 13 lines below it, [here](https://github.com/Mathelab/ALTRE/blob/webgraphs/R/plottingfunctions.R#L304) . Basically, reshape2::melt needs to be replaced by tidyr::gather.

```
melt(df,  variable.name = "key",
                     value.names = "value",
                     id.vars = c("id", "cond"))
# is equivalent to
gather(df, key, value, -id, -trt)

```

**Comment by ewymathe** [comment]
Ok ill change it tonight

**Comment by ewymathe** [comment]
Done

**Comment by Mathelab** [comment]
#
