### ISSUE TITLE
Defined but not used warnings

### ISSUE THREAD

**Issue by rfarouni** [Mathelab/ALTRE#33]
These lines are either not needed or contain unused variables

https://github.com/Mathelab/ALTRE/blob/webgraphs/R/plottingfunctions.R#L747
https://github.com/Mathelab/ALTRE/blob/webgraphs/R/plottingfunctions.R#L810
https://github.com/Mathelab/ALTRE/blob/webgraphs/R/plottingfunctions.R#L816
https://github.com/Mathelab/ALTRE/blob/webgraphs/R/plottingfunctions.R#L1025
https://github.com/Mathelab/ALTRE/blob/webgraphs/R/plottingfunctions.R#L1026

**Comment by Mathelab** [comment]
The first one is needed to remove Notes from Rcheck.

**Comment by rfarouni** [comment]
Rstudio shows an error for the _REaltrecategplot_ object in the first line

**Comment by Mathelab** [comment]
Fixed.
