### ISSUE TITLE
ALTRE not installing on windows

### ISSUE THREAD

**Issue by osubmi784323** [Mathelab/ALTRE#48]
Error message from appveyor: Skipping download of Rtools because src/ directory is missing.
Package required but not available: 'Rsubread'

Rsubread was added as a package to increase performance of package (MUCH faster, eliminates hang-ups), but Rsubread is not available on windows.

Possible solutions that incorporate Rsubread:
MinGW

**Comment by Mathelab** [comment]
Rsubread was made into a suggested package. There are now two available counting functions in the package -- a faster one (getCountsFast) and a slower one (getCounts). Appveyor is no longer erroring.
