### ISSUE TITLE
Error in plotGetCounts()

### ISSUE THREAD

**Issue by alvaropc** [Mathelab/ALTRE#50]
Hi,
trying ALTRE package i have just realysed that there is a problem in plotGetCounts function:

**Error in function_list[[i]](value) : could not find function "hc_add_series_density"**
I was looking for a solution and I saw that highcharter package was uploaded the 17th of January (version 0.5.0) with some changes in the functions, in this case, the new one is hc_add_series.density.

I solved the problem by installing the previous version of highcharter (0.4.0), so in fact I am just wirting this to notice you about that, maybe you want to comment it in README or something.

Thank you for creating the ALTRE package, seems to be very useful!

**Comment by Mathelab** [comment]
Hello,
Many thanks for pointing this out! We will fix this shortly.
Best,
Ewy

**Comment by osubmi784323** [comment]
fixed! Thanks for the heads up.
