### ISSUE TITLE
Error in combine and annotate peaks step

### ISSUE THREAD

**Issue by rnorris1260** [Mathelab/ALTRE#51]
Hi,

I keep getting the following error message when I try to combine and annotate my data:

Warning: Error in [[<-: 180817 elements in value to replace 181590 elements

Am I doing something wrong or is this a bug?

Cheers

**Comment by osubmi784323** [comment]
Hi, thanks for reaching out. It's hard to know if it's an error from you or us with that information.

Would you be comfortable sharing the data you are analyzing with us so we can try to replicate the error? Without it, it will be hard to know what's going on. Also, I will need a copy and paste of every command you ran before getting that error. 

No problem if you prefer not to share your data, but I can't be very helpful without it.

Email: Elizabeth.Baskin@osumc.edu

**Comment by rnorris1260** [comment]
Hi Elizabeth,

Thanks for your message. I'm not sure about data sharing - I will have to check with my supervisor. I will return to the ALTRE analysis when I am finished with some other work so I may contact you again in the future if that's ok. 

Best regards
Richard

**Comment by osubmi784323** [comment]
Sure, no problem, get back to us whenever you're ready.

**Comment by Mathelab** [comment]
Hi Richard,
I am closing this issue for now.  Feel free to reopen an issue should you run into any other problems.
Best,
Ewy
