### ISSUE TITLE
Issue with plotting method comparison

### ISSUE THREAD

**Issue by jentiger82** [Mathelab/ALTRE#52]
I just wanted to inform you about an issue with the plotCompareMethodsAll() function. I wondered about the figures I got with the function, as it looked as if the intensity pie charts and peak pie charts were reversed. Therefore, I checked the code for the function here on Github and found that when the matrix is created for the plot "Intensity" and "Peak" are reversed. So indeed the Intensity pie charts actually show the Peak data and the Peak pie charts show the Intensity data.

Best, Jenny

**Comment by ewymathe** [comment]
Hi Jenny,

Thanks for finding this bug.  We will fix this shortly.

Best,
Ewy

**Comment by Mathelab** [comment]
This should do it!  Thanks again!
