### ISSUE TITLE
Error in downloading sample csv data

### ISSUE THREAD

**Issue by Candlelight-XYJ** [Mathelab/ALTRE#54]
hi i can not download the sample csv data from this site : https://raw.githubusercontent.com/mathelab/AltreDataRepo/master/DNaseEncodeWindows.csv

**Comment by Mathelab** [comment]
Please try the following link:
https://github.com/Mathelab/ALTREsampledata/blob/master/DNaseEncodeExample.csv
All files in the repo can be found here:
https://github.com/Mathelab/ALTREsampledata

**Comment by Candlelight-XYJ** [comment]
Thanks!
